config/routes.rb
Rails.application.routes.draw do
  resources :delivers
  resources :homeworks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deliver.rb
# == Schema Information
#
# Table name: delivers
#
#  id          :bigint           not null, primary key
#  due_date    :date
#  homework_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Deliver < ApplicationRecord
  belongs_to :homework
end

app/models/homework.rb
# == Schema Information
#
# Table name: homeworks
#
#  id          :bigint           not null, primary key
#  title       :string
#  subject     :string
#  due_date    :date
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Homework < ApplicationRecord
  has_many :delivers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/delivers_controller.rb
class DeliversController < ApplicationController
  before_action :set_deliver, only: %i[ show edit update destroy ]

  # GET /delivers or /delivers.json
  def index
    @delivers = Deliver.all
  end

  # GET /delivers/1 or /delivers/1.json
  def show
  end

  # GET /delivers/new
  def new
    @deliver = Deliver.new
  end

  # GET /delivers/1/edit
  def edit
  end

  # POST /delivers or /delivers.json
  def create
    @deliver = Deliver.new(deliver_params)

    respond_to do |format|
      if @deliver.save
        format.html { redirect_to deliver_url(@deliver), notice: "Deliver was successfully created." }
        format.json { render :show, status: :created, location: @deliver }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deliver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivers/1 or /delivers/1.json
  def update
    respond_to do |format|
      if @deliver.update(deliver_params)
        format.html { redirect_to deliver_url(@deliver), notice: "Deliver was successfully updated." }
        format.json { render :show, status: :ok, location: @deliver }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deliver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivers/1 or /delivers/1.json
  def destroy
    @deliver.destroy

    respond_to do |format|
      format.html { redirect_to delivers_url, notice: "Deliver was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deliver
      @deliver = Deliver.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deliver_params
      params.require(:deliver).permit(:due_date, :homework_id)
    end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: %i[ show edit update destroy ]

  # GET /homeworks or /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1 or /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks or /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to homework_url(@homework), notice: "Homework was successfully created." }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1 or /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to homework_url(@homework), notice: "Homework was successfully updated." }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1 or /homeworks/1.json
  def destroy
    @homework.destroy

    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: "Homework was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homework_params
      params.require(:homework).permit(:title, :subject, :due_date, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/delivers/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@deliver) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :due_date
    = f.association :homework

  .form-actions
    = f.button :submit

app/views/delivers/edit.html.haml
%h1 Editing deliver

= render 'form'

= link_to 'Show', @deliver
\|
= link_to 'Back', delivers_path

app/views/delivers/index.html.haml
%h1 Listing delivers

%table
  %thead
    %tr
      %th Due date
      %th Homework
      %th
      %th
      %th

  %tbody
    - @delivers.each do |deliver|
      %tr
        %td= deliver.due_date
        %td= deliver.homework
        %td= link_to 'Show', deliver
        %td= link_to 'Edit', edit_deliver_path(deliver)
        %td= link_to 'Destroy', deliver, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Deliver', new_deliver_path

app/views/delivers/new.html.haml
%h1 New deliver

= render 'form'

= link_to 'Back', delivers_path

app/views/delivers/show.html.haml
%p#notice= notice

%p
  %b Due date:
  = @deliver.due_date
%p
  %b Homework:
  = @deliver.homework

= link_to 'Edit', edit_deliver_path(@deliver)
\|
= link_to 'Back', delivers_path

app/views/homeworks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@homework) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :subject
    = f.input :due_date
    = f.input :description

  .form-actions
    = f.button :submit

app/views/homeworks/edit.html.haml
%h1 Editing homework

= render 'form'

= link_to 'Show', @homework
\|
= link_to 'Back', homeworks_path

app/views/homeworks/index.html.haml
%h1 Listing homeworks

%table
  %thead
    %tr
      %th Title
      %th Subject
      %th Due date
      %th Description
      %th
      %th
      %th

  %tbody
    - @homeworks.each do |homework|
      %tr
        %td= homework.title
        %td= homework.subject
        %td= homework.due_date
        %td= homework.description
        %td= link_to 'Show', homework
        %td= link_to 'Edit', edit_homework_path(homework)
        %td= link_to 'Destroy', homework, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Homework', new_homework_path

app/views/homeworks/new.html.haml
%h1 New homework

= render 'form'

= link_to 'Back', homeworks_path

app/views/homeworks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @homework.title
%p
  %b Subject:
  = @homework.subject
%p
  %b Due date:
  = @homework.due_date
%p
  %b Description:
  = @homework.description

= link_to 'Edit', edit_homework_path(@homework)
\|
= link_to 'Back', homeworks_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinkAgenda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>